# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Perl-Critic
version:      0.04
version_from: lib/Test/Perl/Critic.pm
installdirs:  site
requires:
    File::Spec:                    0
    Perl::Critic:                  0.09
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
