---
abstract: 'Use Perl::Critic in test programs.'
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4'
dynamic_config: 1
generated_by: 'Module::Build version 0.4222, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Perl-Critic
provides:
  Test::Perl::Critic:
    file: lib/Test/Perl/Critic.pm
    version: '1.03'
requires:
  Carp: '0'
  English: '0'
  MCE: '1.827'
  Perl::Critic: '1.105'
  Perl::Critic::Utils: '1.105'
  Perl::Critic::Violation: '1.105'
  Test::Builder: '0.88'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/Perl-Critic/Test-Perl-Critic/issues
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
  repository: git://github.com/Perl-Critic/Test-Perl-Critic.git
version: '1.03'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
