---
name: Test-Perl-Critic
version: 1.01
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
abstract: Use Perl::Critic in test programs.
license: perl
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  Repository: http://perlcritic.tigris.org/svn/perlcritic/trunk/Test-Perl-Critic/
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  English: 0
  Perl::Critic: 1.082
  Perl::Critic::Utils: 1.082
  Perl::Critic::Violation: 1.082
  Test::Builder: 0
  strict: 0
  warnings: 0
build_requires:
  Test::More: 0
provides:
  Test::Perl::Critic:
    file: lib/Test/Perl/Critic.pm
    version: 1.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
