---
abstract: 'Use Perl::Critic in test programs.'
author:
  - 'Jeffrey Thalhammer <thaljef@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.4'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Perl-Critic
provides:
  Test::Perl::Critic:
    file: lib/Test/Perl/Critic.pm
    version: 1.02_002
requires:
  Carp: '0'
  English: '0'
  MCE: '1.52'
  Perl::Critic: '1.105'
  Perl::Critic::Utils: '1.105'
  Perl::Critic::Violation: '1.105'
  Test::Builder: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Perl-Critic/Test-Perl-Critic.git
version: 1.02_002
