---
name: Test-Perl-Critic
version: 0.08
author:
  - Jeffrey Thalhammer <thaljef@cpan.org>
abstract: Use Perl::Critic in test scripts
license: perl
requires:
  Perl::Critic: 0.21
  Perl::Critic::Utils: 0.21
  Perl::Critic::Violation: 0.21
  Test::More: 0
provides:
  Test::Perl::Critic:
    file: lib/Test/Perl/Critic.pm
    version: 0.08
generated_by: Module::Build version 0.2611
